[build]
  command = "hugo --gc --minify -b $URL --themesDir ../../"
  base    = "exampleSite"
  publish = "exampleSite/public"

[build.environment]
  HUGO_THEME = "repo"
  HUGO_VERSION = "0.69.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_VERSION = "0.69.0"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --themesDir ../../"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL --themesDir ../../"
